[package]
name = "day9"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
itertools = "0.12.0"
md5 = "0.7.0"
nom = "7.1.3"
num = "0.4.1"
rand = "0.8.5"
rayon = "1.8.0"
